### ISSUE TITLE
Code improvement suggestions

### ISSUE THREAD

**Issue by cpacia** [simpleledgerinc/goslp#7]
1. The methods to `v1parser.ParseResult` do type assertions that could panic if the type is not correct. This is coupled with the field(s) that are type asserted being exported field. This means it's possible for the fields to be mutated outside the package and panic. I would either make the fields private and provide access via getters, or check the OK on the type assertions to ensure no panic. 

2. You have the toke version and token types enumerated as constants, but not defined as enums which means you have to refer to them as an `int` or `string`. 

For example you do:
```go
const TokenTypeFungible01 int = 0x01

type ParseResult struct {
	TokenType  int
}
```

This could be:
```go
type TokenType int

const TokenTypeFungible01 TokenType = 0x01

type ParseResult struct {
	Type TokenType
}
```

3. The package layout is creating some oddities. For example in goslp/utils.go you have:
```go
if slpMsg.TransactionType == "SEND" 
```

Which should really use an enum instead of a string, like:
```go
if slpMsg.TransactionType == v1parser.Send
```

But this doesn't allow the check to be version agnostic. You might think about moving the enum definition for `TransactionType` into the `goslp` package but then you would have a circular import. Not sure the best way to make this cleaner. 

4. The address code should maybe be put in the `gcash/bchutil` package so as to avoid code duplication. If it was in that package then you could access the unexported fields and simply the code substantially. For example:

```go
func NewSLPAddressPubKeyHash(pkHash []byte, net *chaincfg.Params) (*AddressPubKeyHash, error) {
	addr, err := newAddressPubKeyHash(pkHash, net)
        if err != nil {
             return nil, err
        }
        addr.Prefix = net.SlpAddressPrefix
        return addr, nil
}
```

5. I would use the opcodes from `bchd/txscript` rather than defining `OP_0 int = 0x00`. Also don't want to define them inside the parse function as it takes extra cycles to allocate the memory. 

6. Same thing as above, the extract functions should be outside the parse function. 

7. The `parseCheck` function is a little odd as you have to scroll down to see what it does but it's not saving any lines of code vs just doing:

```go
if len(qtyBuf) != 8 {
        return errors.New("initialQty Must be provided as an 8-byte buffer")
}
```

**Comment by jcramer** [comment]
Thanks for the comments, I will address asap.

**Comment by jcramer** [comment]
1-3, 5, 7 are addressed per your comments.

4. Ok I will do a PR for this tonight or tomorrow morning.

6. For now I have decided to leave the extractUXX type methods inside of the parse function because the methods contain internal variables that are not passed as parameters.  This is part of the parser design that @blockparty-sh worked on which we have been porting between various languages.  We want to keep the parser as similar as possible between the various languages to reduce bugs.

**Comment by jcramer** [comment]
@cpacia WRT item `4) The address code should maybe be put in the gcash/bchutil package`:

Since `params.SlpAddressPrefix` exists only in `simpleledgerinc/bchd` I cannot access this when trying to update a new branch of `bchutil`..  How should I set this up locally to make it work?  Do I need to have the `slp-index` branch add to the remote `gcash/bchd`repo so that I can run `go get github.com/gcash/bchd@<slp-index>` hash during development?

**Comment by jcramer** [comment]
@cpacia Are your comments address?  Lmk and we can close.
